before_script:
- npm install -g mocha
- npm install
language: node_js
node_js:
- '0.10'
notifications:
  email:
  - mirko.diserafino@stamplay.com
  - claudio.petrini@stamplay.com
 after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
